from enum import StrEnum


class AuthorityLevel(StrEnum):
    LOW = "LOW"
    MIDDLE = "MIDDLE"
    HIGH = "HIGH"


class CommitteeType(StrEnum):
    OPERATIONAL_BOARD = "OPERATIONAL_BOARD"
    RISK_MANAGEMENT_COMMITTEE = "RISK_MANAGEMENT_COMMITTEE"
    EXECUTIVE_SAFETY_MANAGEMENT_COMMITTEE = "EXECUTIVE_SAFETY_MANAGEMENT_COMMITTEE"


class RiskWorkflowStatus(StrEnum):
    DRAFT = "DRAFT"
    SUBMITTED_TO_OPERATIONAL_BOARD = "SUBMITTED_TO_OPERATIONAL_BOARD"
    UNDER_OPERATIONAL_BOARD_REVIEW = "UNDER_OPERATIONAL_BOARD_REVIEW"
    APPROVED_AT_OPERATIONAL_BOARD = "APPROVED_AT_OPERATIONAL_BOARD"
    ESCALATED_TO_RISK_MANAGEMENT_COMMITTEE = "ESCALATED_TO_RISK_MANAGEMENT_COMMITTEE"
    UNDER_RISK_MANAGEMENT_COMMITTEE_REVIEW = "UNDER_RISK_MANAGEMENT_COMMITTEE_REVIEW"
    APPROVED_AT_RISK_MANAGEMENT_COMMITTEE = "APPROVED_AT_RISK_MANAGEMENT_COMMITTEE"
    ESCALATED_TO_EXECUTIVE_COMMITTEE = "ESCALATED_TO_EXECUTIVE_COMMITTEE"
    UNDER_EXECUTIVE_COMMITTEE_REVIEW = "UNDER_EXECUTIVE_COMMITTEE_REVIEW"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    RETURNED_FOR_REVISION = "RETURNED_FOR_REVISION"
    CLOSED = "CLOSED"


class RiskLifecycleStatus(StrEnum):
    OPEN = "OPEN"
    UNDER_ANALYSIS = "UNDER_ANALYSIS"
    PENDING_MITIGATION = "PENDING_MITIGATION"
    MITIGATION_IN_PROGRESS = "MITIGATION_IN_PROGRESS"
    PENDING_RESIDUAL_RISK_REVIEW = "PENDING_RESIDUAL_RISK_REVIEW"
    PENDING_ACCEPTANCE = "PENDING_ACCEPTANCE"
    MONITORING = "MONITORING"
    CLOSED = "CLOSED"


class RiskDomain(StrEnum):
    FLIGHT_TEST = "FLIGHT_TEST"
    ENGINEERING = "ENGINEERING"
    MANUFACTURING = "MANUFACTURING"
    QUALITY = "QUALITY"
    PRODUCTION = "PRODUCTION"
    SUPPLY_CHAIN = "SUPPLY_CHAIN"
    OHSE = "OHSE"
    CONTINUED_AIRWORTHINESS = "CONTINUED_AIRWORTHINESS"
    MAINTENANCE = "MAINTENANCE"
    SUPPLIER_INTERFACE = "SUPPLIER_INTERFACE"
    ORGANIZATIONAL = "ORGANIZATIONAL"
    OTHER = "OTHER"


class RiskDecisionType(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    ESCALATE = "ESCALATE"
    RETURN_FOR_REVISION = "RETURN_FOR_REVISION"
    ACCEPT_RESIDUAL_RISK = "ACCEPT_RESIDUAL_RISK"
    CLOSE = "CLOSE"


class AuditAction(StrEnum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    ARCHIVE = "ARCHIVE"
    RESTORE = "RESTORE"
    SUBMIT = "SUBMIT"
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    ESCALATE = "ESCALATE"
    RETURN_FOR_REVISION = "RETURN_FOR_REVISION"
    GENERATE_REPORT = "GENERATE_REPORT"
    LLM_ANALYSIS = "LLM_ANALYSIS"


class RiskAssessmentType(StrEnum):
    INITIAL = "INITIAL"
    RESIDUAL = "RESIDUAL"


class RiskActionStatus(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
