import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from docx import Document
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor
from sqlalchemy.orm import Session

from app.models.committee_meeting import CommitteeMeetingRiskItem
from app.models.enums import CommitteeMeetingStatus
from app.models.risk import RiskDecision
from app.models.user import User
from app.services.committee_meeting_service import (
    CommitteeMeetingBusinessRuleError,
    get_committee_meeting,
)
from app.services.report_service import (
    _add_key_value_paragraph,
    _add_section_heading,
    _add_table,
    _format_bool,
    _format_datetime,
    _format_label,
    _safe_filename,
    _safe_text,
    _set_document_defaults,
)
from app.services.risk_access_service import (
    RiskAccessBusinessRuleError,
    validate_active_user,
)

REPORT_TITLE = "Committee Meeting Minutes"
REPORT_SUBTITLE = "SMS Risk Management Process Tool"


class CommitteeMeetingMinutesReportBusinessRuleError(ValueError):
    pass


def _validate_generator(
    db: Session,
    *,
    meeting_id: uuid.UUID,
    generated_by_user_id: uuid.UUID,
):
    try:
        user = validate_active_user(
            db,
            user_id=generated_by_user_id,
            context="Committee Meeting Minutes report generation",
        )
        meeting = get_committee_meeting(
            db,
            meeting_id=meeting_id,
            requested_by_user_id=user.id,
        )
    except (RiskAccessBusinessRuleError, CommitteeMeetingBusinessRuleError) as exc:
        raise CommitteeMeetingMinutesReportBusinessRuleError(str(exc)) from exc
    if meeting is None:
        raise CommitteeMeetingMinutesReportBusinessRuleError(
            "Committee Meeting Minutes not found"
        )
    return meeting, user


def _user_name(user: User | None, fallback: Any = None) -> str:
    if user is None:
        return _safe_text(fallback)
    return user.display_name or user.email or str(user.id)


def _risk_display_id(item: CommitteeMeetingRiskItem) -> str:
    if item.risk_record is None:
        return str(item.risk_record_id)
    return item.risk_record.risk_id or str(item.risk_record.id)


def _decision_display_id(decision_id: uuid.UUID | None) -> str:
    return str(decision_id) if decision_id is not None else "Not recorded."


def _add_header(
    document,
    *,
    meeting,
    generated_at: datetime,
    generated_by_user_id: uuid.UUID,
) -> None:
    title = document.add_heading(REPORT_TITLE, 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle = document.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle_run = subtitle.add_run(REPORT_SUBTITLE)
    subtitle_run.bold = True
    subtitle_run.font.size = Pt(12)
    subtitle_run.font.color.rgb = RGBColor(72, 101, 129)

    metadata = document.add_table(rows=4, cols=3)
    metadata.style = "Table Grid"
    metadata.alignment = WD_TABLE_ALIGNMENT.CENTER
    values = (
        ("Committee Name", meeting.committee_name),
        ("Authority Level", _format_label(meeting.authority_level)),
        ("Committee Type", _format_label(meeting.committee_type)),
        ("Meeting Title", meeting.title),
        ("Meeting Date", meeting.meeting_date),
        ("Meeting Time UTC", _format_datetime(meeting.meeting_time_utc)),
        ("Location", meeting.location),
        ("Status", meeting.status.value),
        ("Chair", _user_name(meeting.chair_user, meeting.chair_user_id)),
        ("Generated At UTC", _format_datetime(generated_at)),
        ("Generated By User ID", generated_by_user_id),
        ("Report Type", REPORT_TITLE),
    )
    for cell, (label, value) in zip(
        (cell for row in metadata.rows for cell in row.cells),
        values,
        strict=True,
    ):
        cell.text = ""
        paragraph = cell.paragraphs[0]
        paragraph.add_run(f"{label}: ").bold = True
        paragraph.add_run(_safe_text(value))

    status_paragraph = document.add_paragraph()
    status_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    status_run = status_paragraph.add_run(meeting.status.value)
    status_run.bold = True
    status_run.font.size = Pt(14)
    status_run.font.color.rgb = RGBColor(23, 54, 93)

    footer = document.sections[0].footer.paragraphs[0]
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer.add_run(f"{REPORT_TITLE} | {_safe_text(meeting.committee_name)}")


def _attendee_rows(meeting) -> list[list[Any]]:
    return [
        [
            _user_name(attendee.user, attendee.user_id)
            if attendee.user_id
            else attendee.attendee_name,
            attendee.attendee_email or (attendee.user.email if attendee.user else None),
            attendee.role_label,
            _format_label(attendee.attendance_status),
            attendee.notes,
        ]
        for attendee in meeting.attendees
    ]


def _risk_item_rows(meeting) -> list[list[Any]]:
    return [
        [
            item.agenda_item_number,
            _risk_display_id(item),
            _format_label(item.risk_record.domain) if item.risk_record else None,
            (
                _format_label(item.risk_record.workflow_status)
                if item.risk_record
                else None
            ),
            item.risk_record.problem_description if item.risk_record else None,
            item.discussion_summary,
            item.decision_summary,
            _decision_display_id(item.linked_risk_decision_id),
            _format_bool(item.follow_up_required),
            item.follow_up_notes or item.action_items,
        ]
        for item in meeting.risk_items
    ]


def _linked_decision_rows(meeting) -> list[list[Any]]:
    rows = []
    for item in meeting.risk_items:
        decision: RiskDecision | None = item.linked_risk_decision
        if decision is None:
            continue
        rows.append(
            [
                _risk_display_id(item),
                _format_label(decision.decision_type),
                decision.decision_text,
                decision.decided_by_user_id,
                _format_datetime(decision.decided_at),
            ]
        )
    return rows


def generate_committee_meeting_minutes_docx(
    db: Session,
    *,
    meeting_id: uuid.UUID,
    generated_by_user_id: uuid.UUID,
    output_dir: Path | str,
) -> Path:
    meeting, _user = _validate_generator(
        db,
        meeting_id=meeting_id,
        generated_by_user_id=generated_by_user_id,
    )
    if meeting.status not in {
        CommitteeMeetingStatus.DRAFT,
        CommitteeMeetingStatus.FINALIZED,
        CommitteeMeetingStatus.CANCELLED,
    }:
        raise CommitteeMeetingMinutesReportBusinessRuleError(
            "Committee Meeting Minutes status is not supported for export"
        )

    generated_at = datetime.now(timezone.utc)
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    file_path = output_path / (
        f"{_safe_filename(meeting.title)}_{meeting.meeting_date.isoformat()}_"
        "meeting_minutes.docx"
    )

    document = Document()
    _set_document_defaults(document)
    _add_header(
        document,
        meeting=meeting,
        generated_at=generated_at,
        generated_by_user_id=generated_by_user_id,
    )

    _add_section_heading(document, "Section 1 - Attendance")
    if meeting.attendees:
        _add_table(
            document,
            ["Name / User ID", "Email", "Role", "Attendance Status", "Notes"],
            _attendee_rows(meeting),
        )
    else:
        document.add_paragraph("No Attendance records captured.")

    _add_section_heading(document, "Section 2 - Agenda Summary")
    document.add_paragraph(_safe_text(meeting.agenda_summary))

    _add_section_heading(document, "Section 3 - General Discussion Summary")
    document.add_paragraph(_safe_text(meeting.discussion_summary))

    _add_section_heading(document, "Section 4 - Decisions Summary")
    document.add_paragraph(_safe_text(meeting.decisions_summary))

    _add_section_heading(document, "Section 5 - Risk Agenda Items")
    if meeting.risk_items:
        _add_table(
            document,
            [
                "Agenda Item",
                "Risk ID",
                "Domain",
                "Workflow Status",
                "Problem Description",
                "Discussion Summary",
                "Decision Summary",
                "Linked Decision Record",
                "Follow-up Required",
                "Follow-up Notes / Action Items",
            ],
            _risk_item_rows(meeting),
        )
    else:
        document.add_paragraph("No Risk Agenda Items captured.")

    _add_section_heading(document, "Section 6 - Action Items Summary")
    document.add_paragraph(_safe_text(meeting.action_items_summary))

    _add_section_heading(document, "Section 7 - Linked Decision Records")
    linked_decision_rows = _linked_decision_rows(meeting)
    if linked_decision_rows:
        _add_table(
            document,
            ["Risk ID", "Decision Type", "Decision Text", "Decided By", "Decided At"],
            linked_decision_rows,
        )
    else:
        document.add_paragraph("No linked Decision Record entries captured.")

    _add_section_heading(document, "Section 8 - Finalization")
    _add_key_value_paragraph(document, "Status", meeting.status.value)
    _add_key_value_paragraph(
        document,
        "Finalized At",
        _format_datetime(meeting.finalized_at),
    )
    _add_key_value_paragraph(document, "Finalized By", meeting.finalized_by_user_id)
    if meeting.status == CommitteeMeetingStatus.CANCELLED:
        _add_key_value_paragraph(
            document,
            "Cancellation Reason",
            meeting.cancellation_reason,
        )

    _add_section_heading(document, "Section 9 - Disclaimer")
    document.add_paragraph(
        "This Committee Meeting Minutes report is generated from system records. "
        "It supports SMS governance traceability and does not replace formal risk "
        "decision entries, accountable manager acceptance, or required regulatory "
        "documentation."
    )

    try:
        document.save(file_path)
    except Exception as exc:
        raise CommitteeMeetingMinutesReportBusinessRuleError(
            "Failed to generate Committee Meeting Minutes DOCX"
        ) from exc
    return file_path
