import { useEffect, useState } from "react";
import { Navigate } from "react-router-dom";

import { ApiError } from "../api/client";
import {
  downloadGeneratedReport,
  listGeneratedReports,
  saveBlobAsFile,
} from "../api/reports";
import type { GeneratedReportRead } from "../api/types";
import { useAuth } from "../auth/AuthContext";

type ReportsPageState =
  | { status: "loading" }
  | { status: "success"; reports: GeneratedReportRead[] }
  | { status: "error"; message: string };

export function ReportsPage() {
  const { isAuthenticated, token } = useAuth();
  const [reportsState, setReportsState] = useState<ReportsPageState>({
    status: "loading",
  });
  const [downloadError, setDownloadError] = useState<string | null>(null);
  const [downloadingReportId, setDownloadingReportId] = useState<string | null>(
    null,
  );

  useEffect(() => {
    let isCurrent = true;

    if (!token) {
      return;
    }

    const tokenToUse = token;

    async function loadReports() {
      try {
        const reports = await listGeneratedReports(tokenToUse);
        if (isCurrent) {
          setReportsState({ status: "success", reports });
        }
      } catch (error) {
        if (!isCurrent) {
          return;
        }

        setReportsState({
          status: "error",
          message:
            error instanceof ApiError
              ? error.message
              : "Please try again shortly.",
        });
      }
    }

    void loadReports();

    return () => {
      isCurrent = false;
    };
  }, [token]);

  async function handleDownloadReport(report: GeneratedReportRead) {
    if (!token) {
      return;
    }

    setDownloadingReportId(report.id);
    setDownloadError(null);

    try {
      const { blob, filename } = await downloadGeneratedReport(token, report.id);
      saveBlobAsFile(blob, filename);
    } catch (error) {
      setDownloadError(
        error instanceof ApiError ? error.message : "Unable to download report.",
      );
    } finally {
      setDownloadingReportId(null);
    }
  }

  if (!isAuthenticated || !token) {
    return <Navigate replace to="/login" />;
  }

  return (
    <section className="reports-page" aria-labelledby="reports-heading">
      <div className="page-header">
        <div>
          <p className="eyebrow">Report library</p>
          <h1 id="reports-heading">Reports</h1>
          <p>
            Review and download generated risk dossiers and committee meeting
            packs, meeting minutes, and evidence packages.
          </p>
        </div>
      </div>

      {downloadError && (
        <p className="report-error" role="alert">
          {downloadError}
        </p>
      )}

      {reportsState.status === "loading" && (
        <p aria-live="polite" className="workspace-status" role="status">
          Loading generated reports...
        </p>
      )}

      {reportsState.status === "error" && (
        <div aria-live="polite" className="workspace-alert" role="alert">
          <strong>Unable to load generated reports.</strong>
          <span>{reportsState.message}</span>
        </div>
      )}

      {reportsState.status === "success" && reportsState.reports.length === 0 && (
        <section className="workspace-empty" aria-labelledby="empty-reports-heading">
          <h2 id="empty-reports-heading">No reports generated yet.</h2>
          <p>
            Generate a risk dossier from a risk detail page or create a
            Committee Meeting Pack to begin.
          </p>
        </section>
      )}

      {reportsState.status === "success" && reportsState.reports.length > 0 && (
        <ul className="report-list">
          {reportsState.reports.map((report) => (
            <li className="report-item" key={report.id}>
              <div>
                <strong>{formatReportType(report.report_type)}</strong>
                <div className="report-meta">
                  {report.risk_record_id && (
                    <span>Risk record: {report.risk_record_id}</span>
                  )}
                  {report.committee_id && (
                    <span>Committee: {report.committee_id}</span>
                  )}
                  <span>Generated {formatDateTime(report.generated_at)}</span>
                  {report.generated_by_user_id && (
                    <span>Generated by {report.generated_by_user_id}</span>
                  )}
                </div>
              </div>
              <div className="report-actions">
                <button
                  className="report-download-button"
                  disabled={downloadingReportId === report.id}
                  onClick={() => void handleDownloadReport(report)}
                  type="button"
                >
                  {downloadingReportId === report.id
                    ? "Downloading..."
                    : getReportDownloadLabel(report.report_type)}
                </button>
              </div>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}

function formatDateTime(value: string | null | undefined): string {
  if (!value) {
    return "Not available";
  }

  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "Not available" : date.toLocaleString();
}

function formatReportType(value: string): string {
  const labels: Record<string, string> = {
    RISK_DOSSIER_DOCX: "Risk Dossier",
    COMMITTEE_MEETING_PACK_DOCX: "Committee Meeting Pack",
    COMMITTEE_MEETING_MINUTES_DOCX: "Committee Meeting Minutes",
    RISK_EVIDENCE_PACKAGE_ZIP: "Risk Evidence Package",
  };
  return labels[value] || value.replace(/_/g, " ") || "Report";
}

function getReportDownloadLabel(reportType: string): string {
  return reportType.endsWith("_ZIP") ? "Download ZIP" : "Download DOCX";
}
